on:
  push:
    branches: [main]

  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ecmwf-projects/cads-obs-catalogue-manager/.github/workflows/cdm-check.yml@main
    with:
      cdm_ref: ${{ github.ref_name }}
